In [11]:
import pandas as pd
import numpy as np

In [13]:
# load csv files
covid19_data = "covid_19_data.csv"
food_data = "food_data.csv"

# read files into DFs
covid_df = pd.read_csv(covid19_data)
food_df = pd.read_csv(food_data)

In [14]:
covid_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2/24/2020,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2/25/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2/26/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2/27/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2/28/2020,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [15]:
food_df.head()

,Country,Alcoholic Beverages,Animal fats,Animal Products,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetables,Vegetal Products,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0014,0.1973,9.4341,0.0,24.8097,0.2099,0.0350,5.3495,1.2020,...,6.7642,40.5645,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,1.6719,0.1357,18.7684,0.0,5.7817,0.5815,0.2126,6.7861,1.8845,...,11.7753,31.2304,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.2711,0.0282,9.6334,0.0,13.6816,0.5277,0.2416,6.3801,1.1305,...,11.6484,40.3651,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,5.8087,0.0560,4.9278,0.0,9.1085,0.0587,1.7707,6.0005,2.0571,...,2.3041,45.0722,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,3.5764,0.0087,16.6613,0.0,5.9960,0.2274,4.1489,10.7451,5.6888,...,5.4495,33.3233,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%

In [16]:
covid_df['date'] = pd.to_datetime(covid_df['date'])
covid_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [17]:
# RENAME 'LOCATION' COLUMN IN COVID_DF AS 'COUNTRY'
covid_df.rename(columns = {'location':'country'}, inplace = True)
covid_df

,iso_code,continent,country,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85834,ZWE,Africa,Zimbabwe,2021-12-27,205449.0,1098.0,1481.429,4908.0,17.0,14.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
85835,ZWE,Africa,Zimbabwe,2021-12-28,207548.0,2099.0,1397.143,4940.0,32.0,17.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
85836,ZWE,Africa,Zimbabwe,2021-12-29,207548.0,0.0,1163.429,4940.0,0.0,16.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
85837,ZWE,Africa,Zimbabwe,2021-12-30,211728.0,4180.0,1483.429,4997.0,57.0,20.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
85838,ZWE,Africa,Zimbabwe,2021-12-31,213258.0,1530.0,1503.143,5004.0,7.0,19.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [18]:
covid_df.drop(["iso_code","new_cases","new_cases_smoothed","new_deaths","new_deaths_smoothed","new_cases_per_million","new_cases_smoothed_per_million","new_deaths_per_million","new_deaths_smoothed_per_million","reproduction_rate","icu_patients","icu_patients_per_million","hosp_patients","hosp_patients_per_million","weekly_icu_admissions","weekly_icu_admissions_per_million","weekly_hosp_admissions","weekly_hosp_admissions_per_million","new_tests","new_tests_per_thousand","new_tests_smoothed","new_tests_smoothed_per_thousand","tests_units","new_vaccinations","new_vaccinations_smoothed","total_vaccinations_per_hundred","people_vaccinated_per_hundred","people_fully_vaccinated_per_hundred","total_boosters_per_hundred","new_vaccinations_smoothed_per_million","new_people_vaccinated_smoothed","new_people_vaccinated_smoothed_per_hundred","stringency_index","hospital_beds_per_thousand","human_development_index","excess_mortality_cumulative_absolute","excess_mortality_cumulative","excess_mortality","excess_mortality_cumulative_per_million","handwashing_facilities", "extreme_poverty", "female_smokers", "male_smokers", "total_cases_per_million", "total_deaths_per_million", "total_tests_per_thousand"], axis=1, inplace=True)
covid_df

,continent,country,date,total_cases,total_deaths,total_tests,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,...,total_boosters,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,life_expectancy
0,Asia,Afghanistan,2020-02-24,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
1,Asia,Afghanistan,2020-02-25,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
2,Asia,Afghanistan,2020-02-26,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
3,Asia,Afghanistan,2020-02-27,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
4,Asia,Afghanistan,2020-02-28,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85834,Africa,Zimbabwe,2021-12-27,205449.0,4908.0,1678579.0,0.3116,3.2,7222381.0,4105296.0,...,3943.0,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49
85835,Africa,Zimbabwe,2021-12-28,207548.0,4940.0,1686251.0,0.3388,3.0,7226334.0,4107151.0,...,3993.0,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49
85836,Africa,Zimbabwe,2021-12-29,207548.0,4940.0,1693985.0,0.2550,3.9,7238939.0,4112517.0,...,4646.0,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49
85837,Africa,Zimbabwe,2021-12-30,211728.0,4997.0,1701080.0,0.2957,3.4,NaN,NaN,...,NaN,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49
85838,Africa,Zimbabwe,2021-12-31,213258.0,5004.0,1707232.0,0.2858,3.5,7264791.0,4124378.0,...,5245.0,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49

In [19]:
# filter covid df on most recent date (12/31/21)
filtered_covid_df = covid_df[(covid_df['date'] == '2021-12-31')]
filtered_covid_df.head()

,continent,country,date,total_cases,total_deaths,total_tests,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,...,total_boosters,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,life_expectancy
676,Asia,Afghanistan,2021-12-31,158084.0,7356.0,NaN,NaN,NaN,NaN,NaN,...,NaN,39835428,54.422,18.6,2.581,1.337,1803.987,597.029,9.59,64.83
1352,Europe,Albania,2021-12-31,210224.0,3217.0,1423366.0,0.111,9.0,NaN,NaN,...,NaN,2872934,104.871,38.0,13.188,8.643,11803.431,304.195,10.08,78.57
2028,Africa,Algeria,2021-12-31,218432.0,6276.0,NaN,NaN,NaN,NaN,NaN,...,NaN,44616626,17.348,29.1,6.211,3.857,13913.839,278.364,6.73,76.88
2680,Africa,Angola,2021-12-31,81593.0,1770.0,NaN,NaN,NaN,NaN,NaN,...,NaN,33933611,23.890,16.8,2.405,1.362,5819.495,276.045,3.94,61.15
3411,South America,Argentina,2021-12-31,5654408.0,117169.0,28610314.0,0.320,3.1,78135084.0,38771667.0,...,6147048.0,45605823,16.177,31.9,11.198,7.441,18933.907,191.032,5.50,76.67

In [20]:
# drop NA rows from covid df
final_covid_df = filtered_covid_df.dropna()
final_covid_df

,continent,country,date,total_cases,total_deaths,total_tests,positive_rate,tests_per_case,total_vaccinations,people_vaccinated,...,total_boosters,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,life_expectancy
3411,South America,Argentina,2021-12-31,5654408.0,117169.0,28610314.0,0.3200,3.1,78135084.0,38771667.0,...,6147048.0,45605823,16.177,31.9,11.198,7.441,18933.907,191.032,5.50,76.67
5491,Europe,Austria,2021-12-31,1278619.0,13733.0,123579209.0,0.0044,226.4,16585110.0,6667321.0,...,3981330.0,9043072,106.749,44.4,19.202,13.748,45436.686,145.183,6.35,81.54
8196,Europe,Belgium,2021-12-31,2105343.0,28331.0,27361273.0,0.1750,5.7,21712856.0,8933167.0,...,4383478.0,11632334,375.564,41.8,18.571,12.849,42658.576,114.898,4.29,81.63
9513,South America,Bolivia,2021-12-31,599753.0,19680.0,3076104.0,0.2694,3.7,9792844.0,5635100.0,...,548041.0,11832936,10.202,25.4,6.704,4.393,6885.829,204.299,6.89,71.51
11497,South America,Brazil,2021-12-31,22291839.0,619334.0,66100617.0,0.1627,6.1,331273910.0,166195505.0,...,26571077.0,213993441,25.040,33.5,8.552,5.060,14103.452,177.961,8.11,75.88
14903,North America,Canada,2021-12-31,2223735.0,30570.0,52662229.0,0.2292,4.4,68756211.0,31726971.0,...,7615137.0,38067913,4.037,41.4,16.984,10.797,44017.591,105.599,7.37,82.43
16891,South America,Chile,2021-12-31,1806494.0,39115.0,27121207.0,0.0258,38.8,44313177.0,17305441.0,...,11037162.0,19212362,24.282,35.4,11.087,6.938,22767.037,127.993,8.46,80.18
18267,South America,Colombia,2021-12-31,5157440.0,129942.0,29564153.0,0.1350,7.4,64690489.0,38353097.0,...,3324832.0,51265841,44.223,32.2,7.646,4.312,13254.949,124.240,7.44,77.29
22258,Europe,Czechia,2021-12-31,2475729.0,36129.0,47161361.0,0.0970,10.3,15495384.0,6828888.0,...,2411758.0,10724553,137.176,43.3,19.027,11.580,32605.906,227.485,6.82,79.38
22957,Europe,Denmark,2021-12-31,802397.0,3267.0,55354482.0,0.1055,9.5,12094188.0,4787968.0,...,2757808.0,5813302,136.520,42.3,19.677,12.325,46682.515,114.767,6.41,80.90
24299,South America,Ecuador,2021-12-31,549418.0,33681.0,2046961.0,0.2760,3.6,27566331.0,14224604.0,...,1127965.0,17888474,66.939,28.1,7.104,4.458,10581.936,140.448,5.55,77.01
26337,Europe,Estonia,2021-12-31,241408.0,1932.0,2536886.0,0.1241,8.1,1808949.0,842192.0,...,322115.0,1325188,31.033,42.7,19.452,13.491,29481.252,255.569,4.02,78.74
28407,Europe,France,2021-12-31,10018021.0,123805.0,196058691.0,0.1680,6.0,124036273.0,53109166.0,...,22431830.0,67422000,122.578,42.0,19.718,13.079,38605.671,86.060,4.77,82.66
32436,Europe,Greece,2021-12-31,1210853.0,20790.0,47248945.0,0.0581,17.2,17469497.0,7469369.0,...,3530076.0,10370747,83.479,45.3,20.396,14.524,24574.382,175.695,4.55,82.24
33120,North America,Guatemala,2021-12-31,628359.0,16107.0,3281001.0,0.0997,10.0,11310579.0,6535250.0,...,88446.0,18249868,157.834,22.9,4.694,3.016,7423.808,155.898,10.18,74.30
38482,Europe,Ireland,2021-12-31,788559.0,5912.0,10025882.0,0.4043,2.5,9823054.0,3922646.0,...,2271314.0,4982904,69.874,38.7,13.928,8.678,67335.293,126.459,3.28,82.30
39163,Asia,Israel,2021-12-31,1383932.0,8243.0,33793548.0,0.0280,35.7,16768735.0,6574868.0,...,4258023.0,9291000,402.606,30.6,11.733,7.359,33132.320,93.320,6.74,82.97
39864,Europe,Italy,2021-12-31,6125683.0,137402.0,140137606.0,0.0935,10.7,111340173.0,48399756.0,...,19687615.0,60367471,205.859,47.9,23.021,16.240,35220.084,113.151,4.78,83.51
45235,Europe,Latvia,2021-12-31,276674.0,4570.0,5556489.0,0.1197,8.4,2555463.0,1314061.0,...,258627.0,1866934,31.212,43.9,19.754,14.136,25063.846,350.060,4.91,75.29
47242,Europe,Lithuania,2021-12-31,519597.0,7387.0,6905941.0,0.1330,7.5,4131652.0,1917799.0,...,652024.0,2689862,45.135,43.5,19.002,13.778,29524.265,342.989,3.67,75.93
49245,Asia,Malaysia,2021-12-31,2758086.0,31487.0,41845740.0,0.0298,33.6,57774379.0,26013312.0,...,6325625.0,32776195,96.254,29.9,6.293,3.407,26808.164,260.942,16.74,76.16
51943,Asia,Mongolia,2021-12-31,692621.0,2059.0,6392729.0,0.0768,13.0,5340605.0,2265984.0,...,911049.0,3329282,1.980,28.6,4.031,2.421,11840.846,460.043,4.82,69.87
56644,Oceania,New Zealand,2021-12-31,14118.0,51.0,5577146.0,0.0050,198.2,8185286.0,3972078.0,...,357247.0,5126300,18.206,37.9,15.322,9.720,36085.843,128.797,8.08,82.29
59973,Europe,Norway,2021-12-31,394259.0,1305.0,9256762.0,0.2700,3.7,9781881.0,4290203.0,...,1564354.0,5465629,14.462,39.7,16.821,10.813,64800.057,114.316,5.31,82.40
63320,South America,Peru,2021-12-31,2296831.0,202690.0,21790289.0,0.0550,18.2,50965092.0,24802890.0,...,4148177.0,33359415,25.129,29.1,7.151,4.455,12236.706,85.755,5.95,76.74
67364,Asia,Saudi Arabia,2021-12-31,556236.0,8877.0,33310519.0,0.0073,136.6,50894142.0,25017090.0,...,2696173.0,35340680,15.322,31.9,3.295,1.845,49045.411,259.538,17.72,75.13
70718,Europe,Slovenia,2021-12-31,464048.0,5589.0,2081491.0,0.3460,2.9,2762305.0,1250556.0,...,467298.0,2078723,102.619,44.5,19.062,12.930,31400.840,153.493,7.25,81.32
72817,Asia,Sri Lanka,2021-12-31,587245.0,14979.0,6691200.0,0.0702,14.2,33841264.0,15991500.0,...,4006720.0,21497306,341.955,34.1,10.069,5.331,11669.077,197.093,10.68,76.98
74852,Europe,Switzerland,2021-12-31,1332615.0,12217.0,14378018.0,0.2910,3.4,13844683.0,5966981.0,...,2199988.0,8715494,214.243,43.1,18.436,12.644,57410.166,99.739,5.59,83.78
76190,Asia,Thailand,2021-12-31,2223435.0,21698.0,17729894.0,0.0744,13.4,105160269.0,51410504.0,...,7430561.0,69950844,135.132,40.1,11.373,6.890,16277.671,109.861,7.04,77.15
77516,North America,Trinidad and Tobago,2021-12-31,91899.0,2869.0,511257.0,0.2530,4.0,1408384.0,712256.0,...,76184.0,1403374,266.886,36.2,10.014,5.819,28763.071,228.467,10.97,73.51
78845,Asia,Turkey,2021-12-31,9482550.0,82361.0,118984862.0,0.0847,11.8,131646005.0,56914268.0,...,23126843.0,85042736,104.914,31.6,8.153,5.061,25129.341,171.285,12.13,77.69
80472,Europe,Ukraine,2021-12-31,3847226.0,102088.0,16786785.0,0.1988,5.0,28457565.0,14713309.0,...,9515.0,43466822,77.390,41.4,16.462,11.133,7894.393,539.849,7.11,72.06
81876,Europe,United Kingdom,2021-12-31,12964690.0,148737.0,393096602.0,0.1011,9.9,133312817.0,51786768.0,...,34091798.0,68207114,272.898,40.8,18.517,12.527,39753.244,122.137,4.28,81.32
82535,South America,Uruguay,2021-12-31,413383.0,6170.0,4410719.0,0.0773,12.9,6972283.0,2757825.0,...,1536313.0,3485152,19.751,35.6,14.655,10.361,20551.409,160.708,6.93,77.91
85838,Africa,Zimbabwe,2021-12-31,213258.0,5004.0,1707232.0,0.2858,3.5,7264791.0,4124378.0,...,5245.0,15092171,42.729,19.6,2.822,1.882,1899.775,307.846,1.82,61.49

In [21]:
food_df.drop(["Animal fats","Aquatic Products, Other","Miscellaneous","Offals","Oilcrops","Pulses","Spices","Starchy Roots","Stimulants","Sugar Crops","Confirmed","Deaths","Recovered","Active","Population","Unit (all except Population)"], axis=1, inplace=True)
food_df

,Country,Alcoholic Beverages,Animal Products,Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Treenuts,Vegetable Oils,Vegetables,Vegetal Products,Obesity,Undernourished
0,Afghanistan,0.0014,9.4341,24.8097,0.2099,0.0350,5.3495,1.2020,7.5828,1.3489,0.0770,0.5345,6.7642,40.5645,4.5,29.8
1,Albania,1.6719,18.7684,5.7817,0.5815,0.2126,6.7861,1.8845,15.7213,1.5367,0.1515,0.3261,11.7753,31.2304,22.3,6.2
2,Algeria,0.2711,9.6334,13.6816,0.5277,0.2416,6.3801,1.1305,7.6189,1.8342,0.1152,1.0310,11.6484,40.3651,26.6,3.9
3,Angola,5.8087,4.9278,9.1085,0.0587,1.7707,6.0005,2.0571,0.8311,1.8495,0.0061,0.6463,2.3041,45.0722,6.8,25
4,Antigua and Barbuda,3.5764,16.6613,5.9960,0.2274,4.1489,10.7451,5.6888,6.3663,3.8749,0.0253,0.8102,5.4495,33.3233,19.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),2.5952,14.7565,12.9253,0.3389,0.9456,7.6460,3.8328,9.3920,3.4106,0.0009,1.3734,4.1474,35.2416,25.2,21.2
166,Vietnam,1.4591,8.5765,16.8740,0.3077,2.6392,5.9029,4.4382,0.6069,1.2846,0.3070,0.2201,11.9508,41.4232,2.1,9.3
167,Yemen,0.0364,5.7874,27.2077,0.2579,0.5240,5.1344,2.7871,1.8911,5.0468,0.0017,1.0811,3.2135,44.2126,14.1,38.9
168,Zambia,5.7360,6.0197,21.1938,0.3399,1.6924,1.0183,1.8427,1.7570,1.5632,0.0014,0.6657,3.4649,43.9789,6.5,46.7
169,Zimbabwe,4.0552,8.1489,22.6240,0.2678,0.5518,2.2000,2.6142,4.4310,4.6485,0.0518,1.7103,2.3213,41.8526,12.3,51.3

In [22]:
# drop NA rows from food df
final_food_df = food_df.dropna()
final_food_df.head(20)

,Country,Alcoholic Beverages,Animal Products,Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,Milk - Excluding Butter,Sugar & Sweeteners,Treenuts,Vegetable Oils,Vegetables,Vegetal Products,Obesity,Undernourished
0,Afghanistan,0.0014,9.4341,24.8097,0.2099,0.0350,5.3495,1.2020,7.5828,1.3489,0.0770,0.5345,6.7642,40.5645,4.5,29.8
1,Albania,1.6719,18.7684,5.7817,0.5815,0.2126,6.7861,1.8845,15.7213,1.5367,0.1515,0.3261,11.7753,31.2304,22.3,6.2
2,Algeria,0.2711,9.6334,13.6816,0.5277,0.2416,6.3801,1.1305,7.6189,1.8342,0.1152,1.0310,11.6484,40.3651,26.6,3.9
3,Angola,5.8087,4.9278,9.1085,0.0587,1.7707,6.0005,2.0571,0.8311,1.8495,0.0061,0.6463,2.3041,45.0722,6.8,25
5,Argentina,4.2672,19.3454,8.4102,0.9979,0.4693,6.0435,7.0421,10.2328,3.0536,0.0200,0.9541,4.3503,30.6559,28.5,4.6
6,Armenia,0.4014,13.5640,7.2982,0.5783,0.2896,6.0989,2.2675,9.9407,2.6579,0.1108,0.4705,16.7019,36.4358,20.9,4.3
7,Australia,5.5436,21.4175,5.4979,0.4428,1.4264,4.1883,6.7049,12.1018,2.5364,0.3176,1.2798,5.1406,28.5806,30.4,<2.5
8,Austria,7.0215,19.5654,6.2116,0.7884,0.7562,4.6069,4.6810,12.3776,2.6094,0.2367,0.8109,5.1098,30.4338,21.9,<2.5
9,Azerbaijan,3.5969,11.6416,13.0898,0.5593,0.2020,4.7988,2.1513,8.3212,1.5523,0.1906,0.2235,10.0755,38.3584,19.9,<2.5
11,Bangladesh,0.0031,5.1926,29.8045,0.2957,2.5221,2.8655,0.4191,1.8778,0.9285,0.0934,0.7615,3.6405,44.8033,3.4,14.7
12,Barbados,3.5650,12.4976,8.0666,0.7792,3.2750,5.8723,5.8477,2.2041,4.3344,0.0852,0.8677,5.4725,37.5167,24.8,3.9
13,Belarus,3.7563,12.7089,6.2814,0.7565,0.8372,3.5665,4.1893,6.2104,4.0155,0.1399,0.8804,8.7859,37.2904,26.6,<2.5
14,Belgium,5.3730,17.7279,6.6704,0.6487,1.1325,4.1623,3.2370,11.6344,3.6514,0.1309,0.5640,6.8161,32.2637,24.5,<2.5
15,Belize,3.3803,8.6856,11.0700,0.3923,1.0325,12.6094,3.4890,3.6317,3.9798,0.0340,1.0198,4.7721,41.3122,22.4,7.5
16,Benin,5.9019,3.7504,9.6230,0.0711,1.2267,2.9523,1.4107,0.9458,0.6635,0.4028,0.7381,4.1964,46.2493,8.2,10.1
17,Bolivia,2.8956,11.7799,12.3079,0.6626,0.2307,7.5088,6.4098,4.2873,2.5724,0.7084,0.3573,3.2224,38.2165,18.7,17.1
18,Bosnia and Herzegovina,4.7876,12.4319,8.7152,0.2576,0.2465,4.6409,1.8165,9.9443,1.6391,0.0822,0.4205,11.6394,37.5645,19.4,<2.5
19,Botswana,4.2717,14.4486,11.4320,0.1402,0.3551,2.8465,2.2840,11.0217,4.7857,0.0150,1.0065,4.0558,35.5491,16.1,26.4
20,Brazil,4.3629,17.3470,8.4292,0.5042,0.5899,6.0936,6.4784,9.3416,2.7755,0.0513,1.2823,3.3070,32.6537,22.3,<2.5
21,Bulgaria,7.0834,17.2483,8.8750,0.5924,0.4845,3.9812,4.0073,11.5992,2.3627,0.0797,0.7085,6.2037,32.7435,27.4,3.6

In [23]:
final_covid_df.to_csv("cleaned_covid_19_data.csv")
final_food_df.to_csv("cleaned_food_data.csv")