In [142]:
import pandas as pd

In [143]:
who_data = pd.read_csv("WHO-COVID-19-global-table-data.csv")

In [2]:
who_data.head(15)

NameError: name 'who_data' is not defined

In [145]:
who_data["Case_Fatality_Ratio"] = ((who_data["Deaths - cumulative total"]/who_data["Cases - cumulative total"])*100)

In [146]:
who_data.columns = ["WHO Region",
"Cases - cumulative total",
"Cases - cumulative total per 100000 population",
"Cases - newly reported in last 7 days",
"Cases - newly reported in last 7 days per 100000 population",
"Cases - newly reported in last 24 hours",
"Deaths - cumulative total",
"Deaths - cumulative total per 100000 population","Deaths - newly reported in last 7 days",
"Deaths - newly reported in last 7 days per 100000 population",
"Deaths - newly reported in last 24 hours",
"Delete_This",
"Case_Fatality_Ratio"]

who_data = who_data.drop(["Delete_This"], axis=1)

who_data.head()

,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Case_Fatality_Ratio
Global,NaN,516476402,6626.13032,3557106,45.635866,675952,6258023,80.287261,11092,0.142305,1623,1.211676
United States of America,Americas,81178013,24524.88300,492020,148.645000,156260,990599,299.272000,2568,0.776000,339,1.220279
India,South-East Asia,43110586,3123.94600,22468,1.628000,2897,524157,37.982000,237,0.017000,54,1.215834
Brazil,Americas,30574245,14383.85800,113248,53.278000,9709,664192,312.474000,590,0.278000,53,2.172394
France,Europe,28172780,43316.50900,250885,385.743000,48584,143723,220.979000,710,1.092000,123,0.510150

In [148]:
who_data.index.rename("Name", inplace=True)

who_data.reset_index(inplace=True)

who_data.head()

,Name,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours,Case_Fatality_Ratio
0,Global,NaN,516476402,6626.13032,3557106,45.635866,675952,6258023,80.287261,11092,0.142305,1623,1.211676
1,United States of America,Americas,81178013,24524.88300,492020,148.645000,156260,990599,299.272000,2568,0.776000,339,1.220279
2,India,South-East Asia,43110586,3123.94600,22468,1.628000,2897,524157,37.982000,237,0.017000,54,1.215834
3,Brazil,Americas,30574245,14383.85800,113248,53.278000,9709,664192,312.474000,590,0.278000,53,2.172394
4,France,Europe,28172780,43316.50900,250885,385.743000,48584,143723,220.979000,710,1.092000,123,0.510150

In [ ]:
who_data.to_csv("who_data.csv",index=False)